config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users
  resources :memes

  resources :sessions, only: [:new, :create]
  delete '/logout' => 'sessions#destroy', as: :logout
  get '/about' => 'users#about', as: :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meme.rb
class Meme < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    #invoke bcrypt to require AND hash passwords when adding new users:
    has_secure_password
    # 'User' can have many memes, cannot delete 'User' without deleted all of its content
    has_many :memes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    # Returns the value of an instance variable called current_user
    # If @current_user has no value, it assigns it one by finding a user by the ID stored in the session (the cookie provided in the request)
    #  Only does this if the requests cookie contains a users ID to begin with. Otherwise it will return nil...
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    # Takes the value we get from the current_use and converts it into a boolean. Are they logged in? True or false.
    def logged_in?
        !!current_user
    end

    def authorize
        redirect_to new_session_path unless logged_in?
    end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  def index
    @memes = Meme.all
  end

  def show
    @meme = Meme.find(params[:id])
  end

  def new
    @meme = Meme.new
  end

  def create
    @meme = current_user.memes.new(meme_params)
    if @meme.save
      redirect_to user_path(current_user)
    else
      render "new"
    end
  end

  def edit
    @meme = Meme.find(params[:id])
  end

  def update
    @meme = Meme.find(params[:id])
    @meme.caption = params[:meme][:caption]
    @meme.save
    redirect_to user_path(current_user)
  end

  def destroy
    @meme = Meme.find(params[:id])
    @meme.destroy
    redirect_to user_path(current_user)
  end

  private
  def meme_params
    params.require(:meme).permit(:caption, :url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # Renders the login form
  end

  def create # Once user submits login form it will...
    # Look for user with that email...
    @user = User.find_by_email(params[:email])
    # AND the password is correct...
    if @user && @user.authenticate(params[:password])
      # Add the user ID to the session...
      session[:user_id] = @user.id

      flash[:success] = "Welcome, #{@user.username}"
      # Redirect to the users profile/show page...
      # redirect_to user_path(@user)
      redirect_to user_path @user
    else
      #  Otherwise redirect back to the login form page to try again
      flash[:danger] = 'Incorrect email or password. Please try again'
      redirect_to new_session_path
    end
  end

  def destroy
    # Clear the user ID out of the cookie
    session[:user_id] = nil
    # Redirect to the homepage
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, only: [:show, :edit, :update, :destroy]

  def index 
    @users = User.last(5) # Returns last 5 users
    @featured = Meme.all.sample(3) # Returns 3 random memes from Meme table
    @new = Meme.last(3) # Returns the last 3 memes from Meme table
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    # Instantiates a User object to render a form
    @user = User.new
  end

  def create
    # Takes all submitted form info and uses it to create a user account - Then it redirects to new_session_path as defined in.... (CONT)
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    end
  end

  def edit
  end

  def update
  end

  def destroy # Destroys current user and deletes cookie then sends back to signup page
    current_user.destroy
    session[:user_id] = nil
    redirect_to new_user_path
  end

  private # Makes sure only a name, email, password, and password_confirmation can be submitted in the form, for security.
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
    # Password confirmation is a property Bcrypt uses to confirm the user that's signing up entered their password the way they intended.
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemeStr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'partials/navbar' %>
    <div class="container" style="margin-bottom: 100px;">
      

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    
      <%= yield %>
    </div>
  <%= render 'partials/footer' %>
  </body>
</html>

app/views/memes/create.html.erb
<h1>Memes#create</h1>
<p>Find me in app/views/memes/create.html.erb</p>

app/views/memes/destroy.html.erb
<h1>Memes#destroy</h1>
<p>Find me in app/views/memes/destroy.html.erb</p>

app/views/memes/edit.html.erb
<h1>Update/Edit your caption!</h1>

<%= form_for @meme do |m| %>
  <%= m.text_field :caption, placeholder: "Caption" %>
  <%= m.submit %>
<% end %>

app/views/memes/index.html.erb
<h1>Memes#index</h1>
<p>Find me in app/views/memes/index.html.erb</p>

app/views/memes/new.html.erb
<h1>Upload a new Meme!</h1>

<%= form_for @meme do |m| %>
    <%= m.text_field :url, placeholder: "Image URL" %>
    <br>
    <%= m.text_field :caption, placeholder: "Caption..." %>
    <%= m.submit %>
<% end %>

app/views/memes/show.html.erb
<h1>Memes#show</h1>
<p>Find me in app/views/memes/show.html.erb</p>

app/views/memes/update.html.erb
<h1>Memes#update</h1>
<p>Find me in app/views/memes/update.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/partials/_footer.html.erb
<div class="card text-center footer fixed-bottom bg-info">
  <div class="card-body">
    <p class="card-text text-white">MemeStr Copyright 2018 </p>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light p-3 mb-4 bg-info sticky-top shadow-lg rounded">
  <%= link_to 'MemeStr', root_path, class: "navbar-brand text-white"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto text-white">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: "nav-link text-white"%><span class="sr-only">(current)</span>
      </li>
        <%= link_to 'About', about_path, class:'nav-link text-white' %>
      <% if logged_in? %>
        <li class="nav-item">
        <%= link_to "Add Meme", new_meme_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Account', edit_user_path(current_user), class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled text-white font-weight-bold">Logged In As: <%= current_user.username %> </a>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', logout_path, method: 'delete', class: 'nav-link text-white'%>
        </li>
        
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_session_path, class: 'nav-link' %>
        </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/users/about.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <h1 class="display-4 font-weight-bold text-info">MemeStr</h1>
    <p class="lead text-info">About MemeStr</p>
  </div>
</div>

<p class="text-monospace text-center mt-5 pt-5"> MemeStr aims to create a centralized location for all Memes. A place where all Memes can live free, without being judged. A sort of Meme sanctuary, if you will.
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1> Edit account </h1>

<% if logged_in?%>
<%= link_to "Delete Account", user_path(current_user.id), method: "delete" %>
<% end %>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <h1 class="display-4 font-weight-bold text-info">MemeStr</h1>
    <p class="lead text-white">Explore the world of Memes!</p>
  </div>
</div>

<div class="container">
    <div class="row">
        <h2>Explore</h2>
    </div>
<div class="container">
<br>
    <div class="row">
        <div class="col-10">
            <h4>Newest Memes</h4>
        </div>
        <div class="col-2">
            <h4 class="text-right">New MemeStrs</h4>
            <ul class="text-right no-bullets list-group ">
                <% @users.each do |u| %>
                    <li class="text-right list-group-item list-group-item-info badge badge-secondary">
                        <%= link_to(u.username, user_path(u), class: "no-decor") %>
                    </li>
                <% end %>    
            </ul>
        </div>
    </div>
<br>
<h4>Random Memes</h4>
<div class="container">
    <div class="row">
    <% @featured.in_groups_of(3) do | m1, m2, m3 |%>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <%= link_to image_tag(m1.url, class: "card-img-top"), user_path(m1.user) %>
                <div class="card-body">
                    <p class="card-text"><%= m1.caption %></p>
                </div>
            </div>
        </div>
        <% if m2 %>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <%= link_to image_tag(m2.url, class: "card-img-top"), user_path(m2.user) %>
                <div class="card-body">
                    <p class="card-text"><%= m2.caption %></p>
                </div>
            </div>
        </div>
        <% end %>
        <% if m3 %>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <%= link_to image_tag(m3.url, class: "card-img-top"), user_path(m3.user) %>
                <div class="card-body">
                    <p class="card-text"><%= m3.caption %></p>
                </div>
            </div>
        </div>
        <% end %>
    <% end %>
    </div>
</div>


        

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>Sign Up</h1>
    <%= form_for @user do |f| %>  
      <div class="form-group">
        <%= f.label :username, 'Userame*' %>
        <%= f.text_field :username, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email*' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password*' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirm Password*', class: 'col-md-4 control-label' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Create Account', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="mb-5"> 
    <%= @user.username %>'s memes 
</h1>

<div class="container">
    <% @user.memes.in_groups_of(3) do | m1, m2, m3 | %>
    <div class="row mb-5">
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src=<%= m1.url %> alt="Card image cap">
                <div class="card-body">
                    <p class="card-text"><%= m1.caption %></p>
                </div>
            </div>
                <% if current_user == @user %>
                <%= link_to "/memes/#{m1.id}", method: 'delete' do %>
                    <button type="button" class="btn btn-outline-secondary">Remove</button>
                <% end %>
                <%= link_to edit_meme_path(m1)  do %>
                    <button type="button" class="btn btn-outline-secondary">Edit</button>
                <% end %>
                <% end %>
        </div>
        <div class="col-sm">
            <% if m2 %>
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src=<%= m2.url %> alt="Card image cap">
                <div class="card-body">
                    <p class="card-text"><%= m2.caption %></p>
                </div>
            </div>
                <% if current_user == @user %>
                <%= link_to "/memes/#{m2.id}", method: 'delete' do %>
                    <button type="button" class="btn btn-outline-secondary">Remove</button>
                <% end %>
                <%= link_to edit_meme_path(m2) do %>
                    <button type="button" class="btn btn-outline-secondary">Edit</button>
                <% end %>
                <% end %>
            <% end %>
        </div>
        <div class="col-sm">
            <% if m3 %>
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src=<%= m3.url %> alt="Card image cap">
                <div class="card-body">
                    <p class="card-text"><%= m3.caption %></p>
                </div>
            </div>
                <% if current_user == @user %>
                <%= link_to "/memes/#{m3.id}", method: 'delete' do %>
                    <button type"button" class="btn btn-outline-secondary">Remove</button>
                <% end %>
                <%= link_to "/memes/#{m3.id}" do %>
                    <button type="button" class="btn btn-outline-secondary">Edit</button>
                <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
    <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>